
/* /calc/static/src/js/datepicker_params.js defined in bundle 'calc.assets' */
odoo.define('calc.datepicker_params',function(require){'use strict';$.datepicker.regional['es']={closeText:'Cerrar',prevText:'<Ant',nextText:'Sig>',currentText:'Hoy',monthNames:['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],monthNamesShort:['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],dayNames:['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'],dayNamesShort:['Dom','Lun','Mar','Mié','Juv','Vie','Sáb'],dayNamesMin:['Do','Lu','Ma','Mi','Ju','Vi','Sá'],weekHeader:'Sm',dateFormat:'dd/mm/yy',firstDay:1,isRTL:false,showMonthAfterYear:false,yearSuffix:''};});;

/* /calc/static/src/js/query_apostille.js defined in bundle 'calc.assets' */
odoo.define('calc.query_apostille',function(require){'use strict';var ajax=require('web.ajax');var Dialog=require('web.Dialog');var preload=require('cal.preload');var session=require('web.session');const query_apostille=function(){};$(document).ready(function(){if($('model[controller="query_apostille"]').length){if(typeof $('#form_2').attr('filename')!==typeof undefined){search_elect();}else{search_not_elect();}
function search_elect(){$('.panel-heading').find('b').text('Validar firma de Apostilla Electrónica')
$('#form_1').hide();$('#form_2').show();$('#form_1').find('input').each(function(){$(this).prop('required',false);});$('input[name="ufile"]').prop('required',true);};function search_not_elect(){$('.panel-heading').find('b').text('Consulta de Legalización/Apostilla')
$('#form_2').hide();$('#form_1').show();$('#form_1').find('input').each(function(){$(this).prop('required',true);});$('input[name="ufile"]').prop('required',false);};$('#search_elect').click(function(){search_elect();$('#msg_apo_leg').html('');$('#form_1').find('input').each(function(){$(this).val(null);});});$('#search_not_elect').click(function(){search_not_elect();$('#msg_apo_leg').html('');$('input[name="ufile"]').val(null);});$('input[name="ufile"]').change(function(event){var $this=$(this);var file=$this.prop('files')[0];if(file.type.split('/')[1]!=='pdf'||file.size>1600000||file.size<250000){var msg='El archivo a cargar debe ser formato PDF y corresponder a un documento de '
+'Apostilla Electrónica emitido y firmado electrónicamente desde el Sistema '
+'de Legalización y Apostilla Electrónica.';Dialog.alert(this,msg,{confirm_callback:function(){$this.val(null);$this.parent().find('span').html('Cargar PDF').css({'color':'#999999','font-weight':'normal'});},title:'Error de Formato',});}else{$this.parent().find('span').html(file.name).css({'color':'#555555','font-weight':'normal'});}});function resetPage(){$('#query_apostille_response').html('');$('#query_apostille_response').parent().css('display','none');$('#apostille_pdf').html('');}
var dateApostille=$("#date_apostille").datepicker({changeMonth:true,changeYear:true,yearRange:"2010:"+new Date().getFullYear().toString(),dateFormat:"dd-mm-yy",});$("#date_apostille").keyup(function(){this.value='';})
$('#apostille_query').hide();$('#calc_button_go_back').click(function(){$('#apostille_query').hide();$('#panel_heading').show();});$('#calc_button_show_pdf').click(function(e){if($('#apostille_pdf').find('object').length!==1){preload.preload();ajax.jsonRpc('/calc-query-apostille-cal','call',{'identifier_al':$('#identifier_al').val(),'csrf_token':$('input[name="csrf_token"]').val(),}).then(function(response){preload.preloadFinish();if(response.error){$('#apostille_query').hide();$('#panel_heading').show();resetPage();var msg='';if(response.error==='NotFound'){msg='¡Se ha detectado un error, por favor vuelva a realizar la consulta!.';Dialog.alert(this,msg,{confirm_callback:function(){location.reload();},title:'Detención de Petición',});}else{msg='Lo siento, por favor vuelva a realizar la consulta.';Dialog.alert(this,msg,{title:'Error de consulta',});}}else{var datas=response.datas;var apostille='';apostille+=('<object width="100%" height="100%" data="data:application/pdf;base64,');apostille+=(datas);apostille+=('" type="application/pdf" class="internal">');apostille+=('<embed src="data:application/pdf;base64,');apostille+=(datas);apostille+=('" type="application/pdf"/>');apostille+=('</object>');$('#apostille_pdf').html(apostille);$('#apostille_query').show();$('#panel_heading').hide();}});}
$('#apostille_query').show();$('#panel_heading').hide();});$('#calc_button_reset').click(function(){resetPage();$('form')[0].reset();});}});});;

/* /calc/static/src/js/precarga.js defined in bundle 'calc.assets' */
odoo.define('cal.preload',function(require){'use strict';var preload=function(){$("body").css({"overflow-y":"hidden"});var alto=$(window).height();var html="<div id='pre-load-web' align='center' >"
+"<div id='imagen-load'  >"
+"<img  src='/cal/static/src/img/loading.svg'  width='100%' height='100%' />"
+"<br /><h5 style='font-family:sans-serif;'>Cargando...</h5>"
+"</div></div>";$("body").append(html);$("#pre-load-web").css({height:alto+"px"});$("#imagen-load").css({"margin-top":(alto/2)-30+"px"});$(window).load(function(){$("#pre-load-web").fadeOut(1000,function()
{$(this).remove();$("body").css({"overflow-y":"auto"});});});}
var preloadFinish=function(){$("#pre-load-web").fadeOut(100,function(){$(this).remove();$("body").css({"overflow-y":"auto"});});}
$(document).ready(function(){(function(){preload()})();});return{preload:preload,preloadFinish:preloadFinish}});;

/* /calc/static/src/js/remove_footer.js defined in bundle 'calc.assets' */
$(document).ready(function(){$('#footer').remove();});